### PR TITLE
Removed IE11 remnants

### LINKED ISSUE #945: remove IE11 remnants
**Describe the bug**
OpenClinica has dropped support. I think it may be okay to clean up the IE11 remnants from the code now.

### PR DESCRIPTION
**Pull request by MartijnR**
Closes #945 

I relied on the tests to reveal regressions.

### CODE REVIEW

**Comment by MartijnR** [comment]
Some browser test failed. I presume in the 2 year old MS Edge. I updated all browsers to the latest stable version which resolved it. I didn't do any further investigation. If you'd like me to find out exactly which browser and version failed, let me know though!

**Comment by MartijnR** [comment]
Just realized the esbuild config update made no sense as a fix because it modernized the syntax of the JS bundle. Not sure why that worked….

File: src/js/form-model.js [hunk 1]
```diff
@@ -584,20 +505,8 @@ FormModel.prototype.mergeXml = function (recordStr) {
 
     // Remove the primary instance childnode from the original model
     this.xml.querySelector('instance').removeChild(modelInstanceChildEl);
```
Comment (eyelidlessness) [inline src/js/form-model.js:507]: No need to change now, noting for posterity: I think by using `adoptNode`, this can be removed.

**Review by eyelidlessness — APPROVED** [review]
